### ISSUE TITLE
Could not pass event PlayerInteractEvent to OpEconomy v1.4.1

### ISSUE THREAD

**Issue by WeiduKe** [ThisKarolGajda/OpEconomy#2]
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getCustomTagContainer()" because "meta" is null
        at me.opkarol.opeconomy.events.ClickEvent.clickEvent(ClickEvent.java:26) ~[opeconomy-1.4.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-259]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-259]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-259]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:542) ~[patched_1.17.1.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[patched_1.17.1.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:500) ~[patched_1.17.1.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:496) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2295) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.network.protocol.game.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:25) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.network.protocol.game.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:7) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1467) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-259]

**Comment by ThisKarolGajda** [comment]
Thank you for reporting issue, that is fixed now!
[Here](https://github.com/ThisKarolGajda/OpEconomy/releases/tag/1.4.1)
